apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api 
          image: joaotixavier/pedelogo-catalogo:v1.2
          ports:
          - containerPort: 80
            name:  http
          - containerPort: 443
            name:  https
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: configmap-api
          env:
          - name: Mongo__User
            valueFrom:
              configMapKeyRef:
                key: MONGO_INITDB_ROOT_USERNAME
                name: configmap-mongo
          - name: Mongo__Password
            valueFrom:
              configMapKeyRef:
                key: MONGO_INITDB_ROOT_PASSWORD
                name: configmap-mongo
          
            