apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-confrariadocodigotecnologia-com-cert
  namespace: dev
spec:
  secretName: confrariadocodigotecnologia-com-secret
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - "20.190.208.221.nip.io"
