apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxaaa
spec:
  replicas: 8
  selector:
    matchLabels:
      app: nginxaaa
  template:
    metadata:
      labels:
        app: nginxaaa
    spec:
      containers:
      - name: nginxaaa
        image: nginx
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      affinity:
        podAntiAffinity: 
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values: 
                    - nginxaaa
              topologyKey: kubernetes.io/hostname


