apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api-chart-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template: 
    metadata:          
      labels:
        app: {{ .Release.Name }}-api
    spec:            
      containers:
      - name: api
        image: {{ .Values.api.image }}
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "500m"
            memory: "32Mi"
          limits:
            cpu: "500m"
            memory: "64Mi"           
        env:
          - name: Mongo__User
            value: {{ .Values.mongodb.credentials.userName }}
          - name: Mongo__Password
            value: {{ .Values.mongodb.credentials.userPassword }}
          - name: Mongo__Host
            value: {{ .Release.Name }}-mongo-service
          - name: Mongo__DataBase
            value: {{ .Values.mongodb.databaseName }}