version: '3.8'
services:
  api:
    image: fabricioveronez/pedelogo-catalogo:v1
    ports:
      - "8080:80"
    networks:
      - loki
    volumes:
      - "./loki/api:/log"
    depends_on:
      - pedelogo-mongodb
    environment:
      Mongo__Host: "pedelogo-mongodb"
      Mongo__User: "mongouser"
      Mongo__Password: "mongopwd"
      Mongo__Port: "27017"
      Mongo__DataBase: "admin"

  pedelogo-mongodb:
    image: mongo:4.2.8
    volumes:
      - db_mongo:/data/db
    networks:
      - loki
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd

  loki:
    image: grafana/loki:2.7.4
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.0.0
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - "./promtail/config.yaml:/etc/promtail/config.yml"
      - "./logs/api:/logs/api"
      - "./tmp:/tmp"
    networks:
      - loki
    ports:
      - "9080:9080"

volumes:
  db_mongo:
networks:
  loki:
    driver: bridge