apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  type: NodePort

## EXEC kubectl port-forward pod/api-deployment-84f684cdc5-dbpw9 8080:80 para expor api http://localhost:8080/swagger