api:
  image:  fabricioveronez/pedelogo-catalogo:v1
  serviceType: LoadBalancer
  ingress: ["url", "URL"]
  

mongodb:
  tag: 4.2.8
  credentials:
    userName: mongouser
    userPassword: mongopwd
  databaseName: admin