apiVersion: batch/v1
kind: CronJob
metadata:
  name: roleta-job
spec:
  schedule: "*/1 * * * *" 
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 10
      parallelism: 3
      completions: 1
      template:
        spec:
          containers:
          - name: job
            image: kubedevio/roleta
            args:
              - "-w"
              - "5"
              - "-c"
              - "2"
              - "-m"
              - "5"
          restartPolicy: Never