Release "myapi" has been upgraded. Happy Helming!
NAME: myapi
LAST DEPLOYED: Tue Mar 14 21:22:35 2023
NAMESPACE: default
STATUS: pending-upgrade
REVISION: 3
TEST SUITE: None
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
api:
  image: fabricioveronez/pedelogo-catalogo:v1
  serviceType: LoadBalancer
mongodb:
  credentials:
    userName: mongouser
    userPassword: mongopwd
  databaseName: admin
  tag: 4.2.8

HOOKS:
MANIFEST:
---
# Source: api-produto/templates/mongodb-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: myapi-mongo-secret
type: Opaque
data:
    MONGO_INITDB_ROOT_USERNAME: "bW9uZ291c2Vy"
    MONGO_INITDB_ROOT_PASSWORD: "bW9uZ29wd2Q="
---
# Source: api-produto/templates/api-configmap.yaml
apiVersion: v1
kind: ConfigMap

metadata:
    name: myapi-api-configmap
data:
    Mongo__Host: myapi-mongo-service
    Mongo__DataBase: admin
---
# Source: api-produto/templates/api-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: myapi-api-service
spec:
  selector:
    app: myapi-api
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
---
# Source: api-produto/templates/mongodb-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: myapi-mongo-service
spec:
  selector:
    app: myapi-mongodb
  ports:
  - port: 27017
    targetPort: 27017
---
# Source: api-produto/templates/api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapi-api-chart-deployment
spec:
  selector:
    matchLabels:
      app: myapi-api
  template: 
    metadata:          
      labels:
        app: myapi-api
    spec:            
      containers:
      - name: api
        image: fabricioveronez/pedelogo-catalogo:v1
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "500m"
            memory: "32Mi"
          limits:
            cpu: "500m"
            memory: "64Mi"           
        envFrom:
        - configMapRef:
            name: myapi-api-configmap
        env:
          - name: Mongo__User
            valueFrom:
              secretKeyRef:
                key: MONGO_INITDB_ROOT_USERNAME
                name: myapi-mongo-secret
          - name: Mongo__Password
            valueFrom:
              secretKeyRef:
                key: MONGO_INITDB_ROOT_PASSWORD
                name: myapi-mongo-secret
---
# Source: api-produto/templates/mongodb-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapi-mongodb-chart-deployment
spec:
  selector:
    matchLabels:
      app: myapi-mongodb
  template:
    metadata:     
      labels:
        app: myapi-mongodb
    spec:
      containers:
      - name: mongodb
        image: 4.2.8
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: "1500m"
            memory: "1Gi"
          limits:
            cpu: "1500m"
            memory: "1Gi"
        envFrom:
          - secretRef:
              name: myapi-mongo-secret

NOTES:
Instalado
