apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-homolog
  namespace: cert-manager
spec:
  acme: 
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: desenvolvimentodaian@gmail.com
    privateKeySecretRef:
      name: letsencrypt-homolog
    solvers:
    - http01:
        ingress:
          class: traefik